# Generated by Django 3.2.8 on 2021-11-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='num_ans',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.IntegerField(null=True),
        ),
    ]
