# Generated by Django 3.2.8 on 2021-11-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211105_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
