# Generated by Django 3.2.8 on 2021-11-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_answerlikes_questionlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(default='First', to='app.Tags'),
        ),
    ]
