# Generated by Django 3.2.8 on 2021-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211108_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='../static/img/unnamed.png', upload_to=''),
        ),
    ]
