# Generated by Django 3.2.8 on 2021-11-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlikes',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answer'),
        ),
        migrations.AlterField(
            model_name='answerlikes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
