# Generated by Django 3.2.8 on 2021-11-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211110_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='iscorrect',
            field=models.BooleanField(default=False),
        ),
    ]
