# Generated by Django 3.2.8 on 2021-11-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_answer_iscorrect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerlikes',
            old_name='author',
            new_name='user',
        ),
    ]
